import React from 'react'

function IndustryInsights() {
  return (
    <div >
      <section id="industry-insights-section_1" style={{ backgroundColor: 'rgb(2,0,36)' }} class="wow fadeInUp bg-gradient section">
         <div id="industry-insights-container" class="container-lg pt-4 pb-4">
            <div class="row pt-8 pb-4 pt-lg-1 pb-lg-1">
               <div class="col-lg-12 text-left">
                  <ul class="alfanar-breadcrumb font-bold no-margin-bottom">
                     <li class="alfanar-breadcrumb-item" aria-current="page"><a class="text-white" href="/">Home</a></li>
                     <li class="alfanar-breadcrumb-item" aria-current="page"><a class="text-white" href="#">Insights & Newsroom : Industry Insights</a></li>
                  </ul>
               </div>
            </div>
            <div class="row">
               <div class="pt-2 pb-2 col-lg-6 align-self-center wow">
                  <h1 class="text-white font-bold bottom-buffer-2point5rem">Industry Insights</h1>
                  <p class="text-white font-medium extra-large">Whether you are an Executive Director, Administrator, President, or Analyst, the time you dedicate to your organization is valuable. Your members count on you to provide timely information which helps them thrive in their profession. You don’t have time to waste on delayed responses, inaction, and lack of experience. therefore, we offer you the latest industry data generated by our experts to help you decide on the best solution to meet your needs and showcase the experience we provide with top-notch analytic solutions. </p>
               </div>
               <div class="pt-2 pb-2 col-lg-6 align-self-center text-lg-right text-center wow">
                  <img class="w-100" src="/public/final-images/industry-insights-header-img-fix.png"/>
               </div>
            </div>
         </div>
      </section>

      <section id="blogs-section_2" class="wow section">
         <div id="blogs-container" class="container-lg pt-4 pb-4 pt-lg-8 pb-lg-8">
            <div class="row pt-4 pb-4">
               <div class="col-lg-12">
                  <ul class="nav nav-tabs alfanar-tabs">
                     <li class="pb-3">
                        <a class="text-dark-grey pb-lg-3 pb-2 active show" data-toggle="tab" href="#all">
                           All
                        </a>
                     </li>
                     <li class="pb-3">
                        <a data-toggle="tab" href="#opinionpapers">
                           Opinion Papers
                        </a>
                     </li>
                     <li class="pb-3">
                        <a data-toggle="tab" href="#survey">
                           Survey
                        </a>
                     </li>
                     <li class="pb-3">
                        <a data-toggle="tab" href="#futurevisionreport">
                           Future Vision Report
                        </a>
                     </li>
                     <li class="pb-3">
                        <a data-toggle="tab" href="#thoughtleadership">
                           Thought Leadership
                        </a>
                     </li>
                   </ul>
                  <div class="tab-content alfanar-tab-content">
                     <div id="all" class="mt-2 mt-lg-5 mb-3 tab-pane active">
                        <div class="row">
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <p class="small pt-2 mb-0 text-left">By: Hosam Ahmad</p>
                                    <h2 class="pb-3 text-dark-grey pt-2 pr-lg-5 mr-lg-5">All</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <p class="small pt-2 mb-0 text-left">By: Hosam Ahmad</p>
                                    <h2 class="pb-3 text-dark-grey pt-2 pr-lg-5 mr-lg-5">All</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <p class="small pt-2 mb-0 text-left">By: Hosam Ahmad</p>
                                    <h2 class="pb-3 text-dark-grey pt-2 pr-lg-5 mr-lg-5">All</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div id="opinionpapers" class="mt-2 mt-lg-5 mb-3 tab-pane fade">
                        <div class="row">
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <h2 class="pb-3 text-dark-grey pt-2">Opinion Papers</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <h2 class="pb-3 text-dark-grey pt-2">Opinion Papers</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <h2 class="pb-3 text-dark-grey pt-2">Opinion Papers</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div id="survey" class="mt-2 mt-lg-5 mb-3 tab-pane fade">
                        <div class="row">
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <h2 class="pb-3 text-dark-grey pt-2">Survey</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <h2 class="pb-3 text-dark-grey pt-2">Survey</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <h2 class="pb-3 text-dark-grey pt-2">Survey</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div id="futurevisionreport" class="mt-2 mt-lg-5 mb-3 tab-pane fade">
                        <div class="row">
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <h2 class="pb-3 text-dark-grey pt-2">Future Vision Report</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <h2 class="pb-3 text-dark-grey pt-2">Future Vision Report</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <h2 class="pb-3 text-dark-grey pt-2">Future Vision Report</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <div id="thoughtleadership" class="mt-2 mt-lg-5 mb-3 tab-pane fade">
                        <div class="row">
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <h2 class="pb-3 text-dark-grey pt-2">Thought Leadership</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <h2 class="pb-3 text-dark-grey pt-2">Thought Leadership</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                           <div class="col-lg-4 col-sm-12 pt-4 pb-4">
                              <div class="service-block-container">
                                 <div class="service-block-image bg-primary">
                                    <img src="https://www.bernalministries.us/wp-content/uploads/2021/08/Screen-Shot-2021-11-11-at-1.15.31-PM.png"/>
                                 </div>
                                 <div class="service-block-content text-justify bg-section-grey-1 p-3 m-4 pr-lg-4">
                                    <h2 class="pb-3 text-dark-grey pt-2">Thought Leadership</h2>
                                    <p class="pt-2 pb-2 text-dark-grey pr-lg-5">Lorem Ipsum is simply dummy text of the printing and typesetting industry. </p>
                                    <p class="small mb-0 text-right">2021/1/1</p>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
      
    </div>
  )
}

export default IndustryInsights
